# -*- coding: utf-8 -*-
"""Aurotech_MAY_Task_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m7jSIPFZLdmzO8eOxbihY2UoIYgHARSb
"""

pip install qrcode[pil]

import qrcode

def generate_qr_code(data, filename):
    # Create QR code instance
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=10,
        border=4,
    )

    # Add data to the QR code
    qr.add_data(data)
    qr.make(fit=True)

    # Create an image from the QR code
    img = qr.make_image(fill_color="black", back_color="white")

    # Save the image
    img.save(filename)

if __name__ == "__main__":
    # Input data to encode into QR code
    data = input("Enter the data to encode into QR code: ")

    # File name to save the QR code image
    filename = input("Enter the filename to save the QR code image (include extension): ")

    # Generate QR code
    generate_qr_code(data, filename)

    print(f"QR code generated successfully and saved as {filename}")

